sudo: false
language: php
os:
  - linux
php:
  - 5.6
  - 7.0
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
before_script:
  - composer self-update
  - composer install --prefer-dist

script: vendor/bin/phpunit
notifications:
  email: false
