# product gpupo/common-schema:
productId: string
productType: string
department: string
category: string
brand: string
skus:
    -
        skuId: string
        gtin: string
        name: string
        description: string
        color: string
        size: string
        gender: string
        media:
            images:
                -
                    name: string
                    url: string
            videos:
                -
                    name: string
                    url: string
        height: string
        width: string
        depth: string
        weight: string
        listPrice: string
        sellPrice: string
        stock: string
        status: string
        attributes:
            -
                name: string
                value: string
media:
    images:
        -
            name: string
            url: string
    videos:
        -
            name: string
            url: string
attributes:
    -
        name: string
        value: string
