# expands gpupo/common-schema metadata
# version: 2.0
# generated at Mon, 28 May 2018 12:05:33 +0000
Gpupo\CommonSchema\ORM\Entity\People\AlternativePhone:
  type: entity
  table: cs_people_alternative_phone
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\People\AlternativePhoneRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    area_code:
      type: integer
      lenght: 50
      unique: false
      options:
        comment: ''
    extension:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    number:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    verified:
      type: boolean
      lenght: 50
      unique: false
      options:
        comment: ''
    expands:
      type: array
      lenght: 50
      unique: false
      options:
        comment: ''
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
