# expands metadata
# generated at 2018-05-30
Gpupo\CommonSchema\ORM\Entity\People\Document:
  type: entity
  table: cs_people_document
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\People\DocumentRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    doc_type:
      type: string
      lenght: 50
      unique: false
      options: {  }
    doc_number:
      type: string
      lenght: 50
      unique: false
      options: {  }
    expands:
      type: array
      options: {  }
    createdAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          'on': create
    updatedAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          'on': update
    deletedAt:
      type: datetime
      nullable: true
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
      hard_delete: true
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
