# address_delivery metadata
# generated at Mon, 28 May 2018 13:45:03 +0000
Gpupo\CommonSchema\ORM\Entity\Trading\Order\Customer\Customer:
  type: entity
  table: cs_trading_order_customer
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\Order\Customer\CustomerRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    nickname:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    email:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    phone:
      type: manyToMany
      options:
        comment: ''
    alternative_phone:
      type: manyToMany
      options:
        comment: ''
    first_name:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    last_name:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    document:
      type: manyToMany
      options:
        comment: ''
    expands:
      type: array
      options:
        comment: ''
    address_billing:
      type: manyToMany
      options:
        comment: ''
    address_delivery:
      type: manyToMany
      options:
        comment: ''
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
