# description gpupo/common-schema metadata
# version: 2.0
# generated at Mon, 28 May 2018 12:23:16 +0000
Gpupo\CommonSchema\ORM\Entity\Trading\Order\OrderStatusDetail:
  type: entity
  table: cs_trading_order_status_detail
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\Order\OrderStatusDetailRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    code:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    description:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
