# expands gpupo/common-schema metadata
# version: 2.0
# generated at Mon, 28 May 2018 12:27:59 +0000
Gpupo\CommonSchema\ORM\Entity\Trading\Payment\Collector:
  type: entity
  table: cs_trading_payment_collector
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\Payment\CollectorRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    expands:
      type: array
      lenght: 50
      unique: false
      options:
        comment: ''
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
