# expands metadata
# generated at 2018-05-29
Gpupo\CommonSchema\ORM\Entity\People\People:
  type: entity
  table: cs_people
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\People\PeopleRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    nickname:
      type: string
      lenght: 50
      unique: false
      options: {  }
    email:
      type: string
      lenght: 50
      unique: false
      options: {  }
    first_name:
      type: string
      lenght: 50
      unique: false
      options: {  }
    last_name:
      type: string
      lenght: 50
      unique: false
      options: {  }
    expands:
      type: array
      options: {  }
  oneToOne:
    phone:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\People\Phone
      mappedBy: phone
      joinColumn:
        name: phone_id
        referencedColumnName: id
      options: {  }
    alternative_phone:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\People\AlternativePhone
      mappedBy: alternative_phone
      joinColumn:
        name: alternative_phone_id
        referencedColumnName: id
      options: {  }
    document:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\People\Document
      mappedBy: document
      joinColumn:
        name: document_id
        referencedColumnName: id
      options: {  }
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
