# expands gpupo/common-schema metadata
# version: 2.0
# generated at Mon, 28 May 2018 12:27:59 +0000
Gpupo\CommonSchema\ORM\Entity\Trading\Payment\Payment:
  type: entity
  table: cs_trading_payment
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\Payment\PaymentRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    payment_number:
      type: integer
      lenght: 50
      unique: false
      options:
        comment: ''
    collector:
      type: object
      lenght: 50
      unique: false
      options:
        comment: ''
    currency_id:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    status:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    status_code:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    status_detail:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    transaction_amount:
      type: number
      lenght: 50
      unique: false
      options:
        comment: ''
    shipping_cost:
      type: number
      lenght: 50
      unique: false
      options:
        comment: ''
    overpaid_amount:
      type: number
      lenght: 50
      unique: false
      options:
        comment: ''
    total_paid_amount:
      type: number
      lenght: 50
      unique: false
      options:
        comment: ''
    marketplace_fee:
      type: number
      lenght: 50
      unique: false
      options:
        comment: ''
    coupon_amount:
      type: number
      lenght: 50
      unique: false
      options:
        comment: ''
    date_created:
      type: datetime
      lenght: 50
      unique: false
      options:
        comment: ''
    date_last_modified:
      type: datetime
      lenght: 50
      unique: false
      options:
        comment: ''
    card_id:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    reason:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    activation_uri:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    payment_method_id:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    installments:
      type: integer
      lenght: 50
      unique: false
      options:
        comment: ''
    issuer_id:
      type: integer
      lenght: 50
      unique: false
      options:
        comment: ''
    atm_transfer_reference:
      type: object
      lenght: 50
      unique: false
      options:
        comment: ''
    coupon_id:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    operation_type:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    payment_type:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    available_actions:
      type: array
      lenght: 50
      unique: false
      options:
        comment: ''
    installment_amount:
      type: number
      lenght: 50
      unique: false
      options:
        comment: ''
    deferred_period:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    date_approved:
      type: datetime
      lenght: 50
      unique: false
      options:
        comment: ''
    authorization_code:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    transaction_order_id:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    tags:
      type: array
      lenght: 50
      unique: false
      options:
        comment: ''
    expands:
      type: array
      lenght: 50
      unique: false
      options:
        comment: ''
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
