# expands metadata
Gpupo\CommonSchema\ORM\Entity\Organization\Company:
  type: entity
  table: cs_organization_company
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Organization\CompanyRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    nickname:
      type: string
      lenght: 50
      unique: false
      options: {  }
    email:
      type: string
      lenght: 50
      unique: false
      options: {  }
    first_name:
      type: string
      lenght: 50
      unique: false
      options: {  }
    last_name:
      type: string
      lenght: 50
      unique: false
      options: {  }
    internal_id:
      type: bigint
      options: {  }
    expands:
      type: array
      options: {  }
  oneToOne:
    phone:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Organization\Phone
      cascade:
        - persist
        - remove
      options: {  }
    alternative_phone:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Organization\AlternativePhone
      cascade:
        - persist
        - remove
      options: {  }
    document:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Organization\Document
      cascade:
        - persist
        - remove
      options: {  }
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
