# expands metadata
# generated at Mon, 28 May 2018 19:45:26 +0000
Gpupo\CommonSchema\ORM\Entity\Trading\Order\Customer\AddressBilling:
  type: entity
  table: cs_trading_order_customer_address_billing
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\Order\Customer\AddressBillingRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    street:
      type: string
      lenght: 50
      unique: false
      options: {  }
    number:
      type: string
      lenght: 50
      unique: false
      options: {  }
    neighborhood:
      type: string
      lenght: 50
      unique: false
      options: {  }
    reference:
      type: string
      lenght: 50
      unique: false
      options: {  }
    comments:
      type: string
      lenght: 50
      unique: false
      options: {  }
    city:
      type: string
      lenght: 50
      unique: false
      options: {  }
    state:
      type: string
      lenght: 50
      unique: false
      options: {  }
    postalCode:
      type: string
      lenght: 50
      unique: false
      options: {  }
    expands:
      type: array
      options: {  }
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
