# expands metadata
# generated at 2018-05-29
Gpupo\CommonSchema\ORM\Entity\Trading\Payment\Collector\Collector:
  type: entity
  table: cs_trading_payment_collector
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\Payment\Collector\CollectorRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    expands:
      type: array
      options: {  }
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
