# payment metadata
# generated at 2018-05-30
Gpupo\CommonSchema\ORM\Entity\Trading\Trading:
  type: entity
  table: cs_trading
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\TradingRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    expands:
      type: array
      options: {  }
    createdAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          'on': create
    updatedAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          'on': update
    deletedAt:
      type: datetime
      nullable: true
  oneToOne:
    order:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Trading\Order\Order
      options: {  }
    payment:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Trading\Payment\Payment
      options: {  }
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
      hard_delete: true
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
