# expands metadata
# generated at 2018-05-30
Gpupo\CommonSchema\ORM\Entity\People\People:
  type: entity
  table: cs_people
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\People\PeopleRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    nickname:
      type: string
      lenght: 50
      unique: false
      options: {  }
    email:
      type: string
      lenght: 50
      unique: false
      options: {  }
    first_name:
      type: string
      lenght: 50
      unique: false
      options: {  }
    last_name:
      type: string
      lenght: 50
      unique: false
      options: {  }
    expands:
      type: array
      options: {  }
    createdAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          'on': create
    updatedAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          'on': update
    deletedAt:
      type: datetime
      nullable: true
  oneToOne:
    phone:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\People\Phone
      options: {  }
    alternative_phone:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\People\AlternativePhone
      options: {  }
    document:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\People\Document
      options: {  }
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
      hard_delete: true
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
