# order gpupo/common-schema metadata
# version: 2.0
# generated at Mon, 28 May 2018 12:05:33 +0000
Gpupo\CommonSchema\ORM\Entity\Trading\Trading:
  type: entity
  table: cs_trading
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\TradingRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    expands:
      type: array
      lenght: 50
      unique: false
      options:
        comment: ''
    order:
      type: object
      lenght: 50
      unique: false
      options:
        comment: ''
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
