# expands metadata
# generated at Mon, 28 May 2018 18:42:49 +0000
Gpupo\CommonSchema\ORM\Entity\People\Phone:
  type: entity
  table: cs_people_phone
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\People\PhoneRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    area_code:
      type: bigint
      options: {  }
    extension:
      type: string
      lenght: 50
      unique: false
      options: {  }
    number:
      type: string
      lenght: 50
      unique: false
      options: {  }
    verified:
      type: boolean
      options: {  }
    expands:
      type: array
      options: {  }
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
