# unit_price metadata
# generated at 2018-05-30
Gpupo\CommonSchema\ORM\Entity\Trading\Order\Shippings\Products\Product:
  type: entity
  table: cs_trading_order_shipping_product
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\Order\Shippings\Products\ProductRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    expands:
      type: array
      options: {  }
    seller_product_id:
      type: string
      lenght: 50
      unique: false
      options: {  }
    title:
      type: string
      lenght: 50
      unique: false
      options: {  }
    gtin:
      type: string
      lenght: 50
      unique: false
      options: {  }
    variation_attributes:
      type: array
      options: {  }
    sale_fee:
      type: decimal
      precision: 10
      scale: 2
      options: {  }
    quantity:
      type: bigint
      options: {  }
    unit_price:
      type: decimal
      precision: 10
      scale: 2
      options: {  }
    createdAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          'on': create
    updatedAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          'on': update
    deletedAt:
      type: datetime
      nullable: true
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
      hard_delete: true
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
