# expands metadata
# generated at 2018-05-30
Gpupo\CommonSchema\ORM\Entity\Trading\Payment\Collector\Collector:
  type: entity
  table: cs_trading_payment_collector
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\Payment\Collector\CollectorRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    expands:
      type: array
      options: {  }
    createdAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          'on': create
    updatedAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          'on': update
    deletedAt:
      type: datetime
      nullable: true
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false
      hard_delete: true
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
