# expands gpupo/common-schema metadata
# version: 2.0
# generated at Fri, 25 May 2018 20:35:48 +0000
Gpupo\CommonSchema\ORM\Entity\People\Document:
  type: entity
  table: cs_people_document
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\People\DocumentRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    doc_type:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    doc_number:
      type: string
      lenght: 50
      unique: false
      options:
        comment: ''
    expands:
      type: array
      lenght: 50
      unique: false
      options:
        comment: ''
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
