# expands metadata
# generated at Mon, 28 May 2018 14:33:56 +0000
Gpupo\CommonSchema\ORM\Entity\Trading\Payment\Collector:
  type: entity
  table: cs_trading_payment_collector
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Trading\Payment\CollectorRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    expands:
      type: array
      options: {  }
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
