# scope metadata
Gpupo\CommonSchema\ORM\Entity\Application\API\OAuth\Client\AccessToken:
  type: entity
  table: cs_application_API_OAuth_access_token
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Application\API\OAuth\Client\AccessTokenRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    access_token:
      type: string
      lenght: 50
      unique: false
      options: {  }
    expires_in:
      type: bigint
      nullable: true
      options: {  }
    live_mode:
      type: boolean
      nullable: true
      options: {  }
    refresh_token:
      type: string
      lenght: 50
      unique: false
      options: {  }
    scope:
      type: string
      lenght: 50
      unique: false
      options: {  }
    token_type:
      type: string
      lenght: 50
      unique: false
      options: {  }
    user_id:
      type: bigint
      nullable: true
      options: {  }
  uniqueConstraints: {  }
  oneToOne:
    item:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Application\API\OAuth\Client\Item
      inversedBy: access_token
      joinColumn:
        name: item_id
        referencedColumnName: id
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
