# access_token metadata
Gpupo\CommonSchema\ORM\Entity\Application\API\OAuth\Client:
  type: entity
  table: cs_application_API_OAuth_client
  repositoryClass: Gpupo\CommonSchema\ORM\Repository\Application\API\OAuth\ClientRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    client_id:
      type: string
      lenght: 50
      unique: false
      options: {  }
    client_secret:
      type: string
      lenght: 50
      unique: false
      options: {  }
    description:
      type: string
      lenght: 50
      unique: false
      options: {  }
    external_id:
      type: bigint
      nullable: true
      options: {  }
    name:
      type: string
      lenght: 50
      unique: false
      options: {  }
  oneToOne:
    access_token:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Application\API\OAuth\AccessToken
      cascade:
        - persist
        - remove
      options: {  }
      mappedBy: client
    provider:
      targetEntity: Gpupo\CommonSchema\ORM\Entity\Application\API\OAuth\Provider
      inversedBy: client
      joinColumn:
        name: provider_id
        referencedColumnName: id
  uniqueConstraints:
    client_id_idx:
      columns:
        - client_id
  lifecycleCallbacks:
    prePersist: {  }
    postPersist: {  }
